import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Cardio() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cardiology</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Cardiology tests
        </h1>

        <p className={styles.description}>
        <a href="../../">Go back to the Main Page</a>
        </p>

        <div className={styles.grid}>
        <a href="https://nextjs.org/docs" className={styles.card}>
          <h2>Suite 1 &rarr;</h2>
            <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
            </p>
          </a>
        <a href="https://nextjs.org/docs" className={styles.card}>
          <h2>Suite 2 &rarr;</h2>
            <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
            </p>
          </a>
          <a href="https://nextjs.org/docs" className={styles.card}>
          <h2>Suite 3 &rarr;</h2>
            <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
          <h2>Suite 4 &rarr;</h2>
            <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Suite 5 &rarr;</h2>
            <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Suite 6 &rarr;</h2>
            <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
